// conversation_react/src/Components/Conversation.jsx
import { useEffect, useState } from "react";
import "../css/conversation.css";

export function Conversations({ active_conversation_prop, name_prop }) {
  const [messages, setMessages] = useState([]);
  const [messageText, setMessageText] = useState("");
  //   const [isSignedInUser, setIsSignedInUser] = useState(false);

  useEffect(() => {
    active_conversation_prop.getMessages().then((newMessages) => {
      setMessages((prevState) => [...prevState, ...newMessages.items]);
    });

  }, [active_conversation_prop]);

  useEffect(() => {
    active_conversation_prop.on("messageAdded", (message) => {
      setMessages([...messages, message]);
    });
  }, [active_conversation_prop, messages]);

  const sendMessage = () => {
    active_conversation_prop.sendMessage(messageText).then(() => {
      setMessageText("");
    });
  };

  const handleValueInput = (e) => {
    setMessageText(e.target.value);
  };

  return (
    <div id="conversation">
      <div className="conversation-container">
        {messages.map((message, index) => (
          <div
            key={index}
            className={`bubble-container ${
              message?.state?.author === name_prop ? "myMessage" : ""
            }`}
          >
            <div className="bubble">
              <div className="name">{message?.state?.author}:</div>
              <div className="message">{message?.state?.body}</div>
            </div>
          </div>
        ))}
      </div>
      <div className="input-container">
        <input
          type="text"
          onChange={handleValueInput}
          value={messageText}
          placeholder="Enter your message"
        />
        <button onClick={sendMessage}>Send message</button>
      </div>
    </div>
  );
}

// conversations-project/src/components/Conversation.vue
<template>
  <div id="conversation">
    <div class="conversation-container">
      <div
        v-for="message in messages"
        :key="message.index"
        class="bubble-container"
        :class="{ myMessage: message?.state?.author === name }"
      >
        <div class="bubble">
          <div class="name">{{ message?.state?.author }}:</div>
          <div class="message">{{ message?.state?.body }}</div>
        </div>
      </div>
    </div>
    <div class="input-container">
      <input
        @keyup.enter="sendMessage"
        v-model="messageText"
        placeholder="Enter your message"
      />
      <button @click="sendMessage">Send message</button>
    </div>
  </div>
</template>

<style scoped>
.conversation-container {
  margin: 0 auto;
  max-width: 400px;
  height: 600px;
  padding: 0 20px;
  border: 3px solid #f1f1f1;
  overflow: scroll;
}

.bubble-container {
  text-align: left;
}

.bubble {
  border: 2px solid #f1f1f1;
  background-color: #fdfbfa;
  border-radius: 5px;
  padding: 10px;
  margin: 10px 0;
  width: 230px;
  float: right;
}

.myMessage .bubble {
  background-color: #abf1ea;
  border: 2px solid #87e0d7;
  float: left;
}

.name {
  padding-right: 8px;
  font-size: 11px;
}

::-webkit-scrollbar {
  width: 10px;
}

::-webkit-scrollbar-track {
  background: #f1f1f1;
}

::-webkit-scrollbar-thumb {
  background: #888;
}

::-webkit-scrollbar-thumb:hover {
  background: #555;
}
</style>

<script>
export default {
    props: ["activeConversation", "name"],
    data() {
        return {
            messages: [],
            messageText: "",
            isSignedInUser: false
        }
    }, 
    mounted(){
        this.activeConversation.getMessages() 
            .then((newMessages) => {
                this.messages = [...this.messages, ...newMessages.items]
            })
        
        this.activeConversation.on("messageAdded", (message) => {
            this.messages = [...this.messages, message]
        })
    },
    methods: {
        sendMessage: function(){
            this.activeConversation.sendMessage(this.messageText)
                .then(() => {
                    this.messageText = ""
                })
        }
    }
}
</script>
